title: Venta de Libros Online
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  La mejor tienda online para comprar tus libros favoritos
baseurl: "/PaginaLibros" # the subpath of your site, e.g. /blog
url: "https://Akim0423.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed


